name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/stalhub
            git fetch origin main
            git reset --hard origin/main

            export GIT_COMMIT_SHA=$(git rev-parse HEAD)

            docker build --build-arg GIT_COMMIT_SHA=$GIT_COMMIT_SHA -t stalhub_frontend:$GIT_COMMIT_SHA .
            docker stack deploy -c docker-compose.yml stalhub